
init:
	npm install
	cd ./src && ../node_modules/.bin/bower install

run_server:
	npm run run_dev_server

build:
	npm run build_watch

unit_test:
	./node_modules/.bin/mocha

codecoverage:
	./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha

