# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_auto_20161121_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('listname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
        migrations.AddField(
            model_name='custom_list',
            name='cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.Customer'),
        ),
        migrations.AddField(
            model_name='custom_list',
            name='lname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.List'),
        ),
    ]
